--liquibase formatted sql
--changeset author:Andrey_Mahov

CREATE TABLE PASSPORTS
(
    ID       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NUMBER   INTEGER,
    OWNER_ID INTEGER UNIQUE,
    STATUS   CHARACTER(100) not null default 'ACTIVE'
);

--rollback drop table PASSPORTS;