--liquibase formatted sql
--changeset author:Andrey_Mahov

CREATE TABLE CITIZENS
(
    ID            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NAME          CHARACTER(100),
    SURNAME       CHARACTER(100),
    GENDER        CHARACTER(100),
    STATUS        CHARACTER(100) not null default 'ACTIVE',
    PLACE_OF_WORK CHARACTER(100)
);

--rollback drop table CITIZENS;
