spring:
  application:
    name: house-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

  datasource:
    url: jdbc:postgresql://localhost:5432/houses
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    show-sql: true

  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
  profiles:
    active: jpa

  kafka:
    consumer:
      group-id: delete_citizen_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:29092

springdoc:
  swagger-ui:
    enabled: true
    path: /houses/swagger-ui.html

server:
  port: 8083

url:
  houses-service: api/v1/house-service/houses



